name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.workflow || github.run_id }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image name
        id: image
        run: |
          otel_version=$(yq -r '.dist.otel_version' builder-config.yml)
          docker_image=$(yq -r '.dist.name' builder-config.yml)
          name="${{ secrets.DOCKERHUB_USERNAME }}/${docker_image}"
          echo "image_name=${name}" >> "${GITHUB_OUTPUT}"
          echo "otel_version=${otel_version}" >> "${GITHUB_OUTPUT}"

      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          tags: |
            ${{ steps.image.outputs.image_name }}:${{ steps.image.outputs.otel_version }}
            ${{ steps.image.outputs.image_name }}:latest
          push: ${{ github.event_name == 'workflow_dispatch' }}
          no-cache: true
